name: 'Create And Publish Release'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  # build:
  #   name: Run Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 'Checkout'
  #       uses: actions/checkout@v1

  #     - name: 'Set up JDK 1.8'
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8

  #     - name: 'Setup Build'
  #       run: 'chmod 777 gradlew'

  #     - name: 'Build with Gradle'
  #       id: build
  #       env: {USE_ALPHAS: false}
  #       run: './gradlew setupGithubActions build --max-workers=1'

  generate_changelog:
    name: Create and Commit Changelog
    #needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Update main CHANGELOG.md
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Generate Curseforge Changelog
        uses: Helmisek/conventional-changelog-generator@v1.0.6-release
        id: changelog-generator
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: "fix:Bug Fixes,feat:Features,refactor:Refactoring"
          template-path: "./.github/workflows/CURSEFORGE_CHANGELOG.tpl.md"
          current-tag: ${{ steps.get_version.outputs.VERSION }}

      - name: Commit Changelogs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: 1.12.2
          commit_message: 'docs: update changelogs for ${{ github.ref_name }}'

  publish_to_curseforge:
    name: Publish to CurseForge
    needs: generate_changelog
    runs-on: ubuntu-latest
    steps:
      - name: "Upload to CurseForge"
        uses: itsmeow/curseforge-upload@master
        with:
          changelog: "Changelog not added yet..."
          changelog_type: html
        # display_name: use the filename
          file_path: "/build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}.jar"
          game_endpoint: minecraft
          relations: "${{ steps.build.outputs.curse_relations }}"
          game_versions: "${{ steps.build.outputs.curse_versions }}"
          project_id: "${{ steps.build.outputs.curse_project_id }}"
          release_type: release
          token: "${{ secrets.CURSEFORGE_API_TOKEN }}"
