name: 'Create Release with Changelogs'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  changelog_job:
    runs-on: ubuntu-latest
    name: Create and Commit Changelog
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Update main CHANGELOG.md
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
        
      - name: Generate Curseforge Changelog
        uses: Helmisek/conventional-changelog-generator@v1.0.6-release
        id: changelog-generator
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: "fix:Bug Fixes,feat:Features,refactor:Refactoring"
          template-path: "/.github/workflows/CURSEFORGE_CHANGELOG.tpl.md"
          current-tag: ${{ steps.get_version.outputs.VERSION }}
      #    tag-regex: "-release"
          
      #- name: Print version
      #  run: echo ${{ steps.get_version.outputs.VERSION }}
     # - name: Print changelog to file
     #   uses: DamianReeves/write-file-action@master
     #   with:
     #     path: ${{ github.workspace }}/.github/CURSEFORGE_CHANGELOG.md
     #     contents: |
     #       ${{steps.changelog-generator.outputs.changelog}}
     #     write-mode: overwrite
          
     # - name: cat CURSEFORGE_CHANGELOG.md
     #   run: cat ${{ github.workspace }}/.github/CURSEFORGE_CHANGELOG.md
     #   
      - name: Commit CURSEFORGE_CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: 1.12.2
          commit_message: 'docs: update changelogs for ${{ github.ref_name }}'
